#!/bin/sh

COLOR_NORMAL="\033[39m"
COLOR_RED="\033[31m"
COLOR_GREEN="\033[32m"
COLOR_CYAN="\033[36m"

CLI_INSTALL_PATH="${HOME}/usr/local/clif"

install_deps() {
  which -s brew
  if [[ $? != 0 ]] ; then
    # install Homebrew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    brew update
  fi

  brew install git

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Dependencies installed ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
}

# to clone the CLI wee need to ensure git is installed
checks_req() {
  # most versions of MacOS will already have Git installed, and you can activate 
  # it through the terminal with git version
  git --version 2>&1 >/dev/null || {
    echo "${COLOR_RED}clif-cli:${COLOR_NORMAL} Please install git. See: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git for further information."
    exit 1
  }

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Check requirements ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
}

# we need to give CLI commands read, write, and execute permissions
grant_permissions() {
  # chmod is the command and system call used to change the access permissions 
  # of file system

  # here we use octal value of 775 on the CLI directory
  chomd -R 775 "${CLI_INSTALL_PATH}"

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Grant permissions ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
}

# adds the kone alias to the users .bash_profile
update_bash_profile() {
  bash_profile="${HOME}/.bash_profile"
  if [ ! -f "${bash_profile}" ]; then
    echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} No such file: .bash_profile"
    
    # a typical install of macOS won't create a .bash_profile for you, so let
    # us do it now
    touch ${bash_profile} 

    echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Create .bash_profile ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
  fi

  # add the alias to the bash_profile
  echo "" >> "${bash_profile}" # add a blank line
  echo "# clif CLI" >> "${bash_profile}"
  echo "alias clif=\"${CLI_INSTALL_PATH}/cli"\" >> "${bash_profile}" # append the alias

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Alias added to .bash_profile ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
}

get_project() {
  git clone --quiet git@github.com:konecorp/kone-mobile-fsm-cli.git > /dev/null # hide the output
  if [ ! $? -eq 0 ]; then
    echo >&2 "${COLOR_RED}clif-cli: Error:${COLOR_NORMAL} Could not download the CLI."
    exit 1
  fi

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Download the CLI ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
}

is_cli_installed() {
  # the CLI is already installed and can simply be updated, so we can exit
  if [ -d "${CLI_INSTALL_PATH}" ]; then
    echo "${COLOR_RED}clif-cli:${COLOR_NORMAL} The CLI is already installed. Please run '$ clif update'."
    exit 1
  fi
}

copy_to() {
  # copy the contents of the cloned project by moving it to the specified 
  # install path
  cli_dir="${HOME}/usr/local/"
  [ ! -d "${cli_dir}" ] && mkdir -p ${cli_dir}

  mv "kone-mobile-fsm-cli" "${CLI_INSTALL_PATH}"

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Copy the CLI to '${CLI_INSTALL_PATH}' ... ${COLOR_GREEN}OK${COLOR_NORMAL}"
}

setup() {
  is_cli_installed
  checks_req
  get_project
  copy_to
  update_bash_profile

  echo "${COLOR_CYAN}clif-cli:${COLOR_NORMAL} Setup completed successfully. Please quit the terminal and relaunch."
}

setup
